<!--
/**
 * Magenizr AdminBranding
 *
 * @copyright   Copyright (c) 2021 - 2024 Magenizr (https://magenizr.com.au)
 * @license     https://magenizr.com.au/license Magenizr EULA
 */
-->

<?php if ($block->isAdditionalTextEnabled() && $block->getHelper()->isEnabled()): ?>
    <div id="magenizr-adminbranding">
        <p class="border-top"><?= /* @noEscape */ $block->getAdditionalText() ?></p>
    </div>
<?php endif; ?>
