<!--
/**
 * Magenizr AdminBranding
 *
 * @category    Magenizr
 * @package     Magenizr_AdminBranding
 * @copyright   Copyright (c) 2021 Magenizr (https://agency.magenizr.com)
 * @license     https://www.magenizr.com/license Magenizr EULA
 */
-->

<?php if ($block->isAdditionalTextEnabled() && $block->getHelper()->isEnabled()): ?>
    <div id="magenizr-adminbranding">
        <p class="border-top"><?= $block->getAdditionalText(); ?></p>
    </div>
<?php endif; ?>
